export interface Country {
    name: string;
    code: string;
    flag: string; // Emoji flag
}

export const COUNTRIES: Country[] = [
    { name: 'India', code: 'IN', flag: '🇮🇳' },
    { name: 'United States', code: 'US', flag: '🇺🇸' },
    { name: 'Australia', code: 'AU', flag: '🇦🇺' },
    { name: 'Germany', code: 'DE', flag: '🇩🇪' },
    { name: 'France', code: 'FR', flag: '🇫🇷' },
    { name: 'United Kingdom', code: 'GB', flag: '🇬🇧' },
    { name: 'Canada', code: 'CA', flag: '🇨🇦' },
    { name: 'Japan', code: 'JP', flag: '🇯🇵' },
    { name: 'China', code: 'CN', flag: '🇨🇳' },
    { name: 'Brazil', code: 'BR', flag: '🇧🇷' },
    { name: 'Mexico', code: 'MX', flag: '🇲🇽' },
    { name: 'Spain', code: 'ES', flag: '🇪🇸' },
    { name: 'Italy', code: 'IT', flag: '🇮🇹' },
    { name: 'Russia', code: 'RU', flag: '🇷🇺' },
    { name: 'South Korea', code: 'KR', flag: '🇰🇷' },
    { name: 'Netherlands', code: 'NL', flag: '🇳🇱' },
    { name: 'Sweden', code: 'SE', flag: '🇸🇪' },
    { name: 'Norway', code: 'NO', flag: '🇳🇴' },
    { name: 'Denmark', code: 'DK', flag: '🇩🇰' },
    { name: 'Finland', code: 'FI', flag: '🇫🇮' },
    { name: 'Poland', code: 'PL', flag: '🇵🇱' },
    { name: 'Turkey', code: 'TR', flag: '🇹🇷' },
    { name: 'Argentina', code: 'AR', flag: '🇦🇷' },
    { name: 'South Africa', code: 'ZA', flag: '🇿🇦' },
    { name: 'Egypt', code: 'EG', flag: '🇪🇬' },
    { name: 'Nigeria', code: 'NG', flag: '🇳🇬' },
    { name: 'Kenya', code: 'KE', flag: '🇰🇪' },
    { name: 'Thailand', code: 'TH', flag: '🇹🇭' },
    { name: 'Indonesia', code: 'ID', flag: '🇮🇩' },
    { name: 'Philippines', code: 'PH', flag: '🇵🇭' },
    { name: 'Vietnam', code: 'VN', flag: '🇻🇳' },
    { name: 'Malaysia', code: 'MY', flag: '🇲🇾' },
    { name: 'Singapore', code: 'SG', flag: '🇸🇬' },
    { name: 'New Zealand', code: 'NZ', flag: '🇳🇿' },
    { name: 'Ireland', code: 'IE', flag: '🇮🇪' },
    { name: 'Portugal', code: 'PT', flag: '🇵🇹' },
    { name: 'Greece', code: 'GR', flag: '🇬🇷' },
    { name: 'Belgium', code: 'BE', flag: '🇧🇪' },
    { name: 'Switzerland', code: 'CH', flag: '🇨🇭' },
    { name: 'Austria', code: 'AT', flag: '🇦🇹' },
    { name: 'Czech Republic', code: 'CZ', flag: '🇨🇿' },
    { name: 'Hungary', code: 'HU', flag: '🇭🇺' },
    { name: 'Romania', code: 'RO', flag: '🇷🇴' },
    { name: 'Ukraine', code: 'UA', flag: '🇺🇦' },
    { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦' },
    { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪' },
    { name: 'Israel', code: 'IL', flag: '🇮🇱' },
    { name: 'Chile', code: 'CL', flag: '🇨🇱' },
    { name: 'Colombia', code: 'CO', flag: '🇨🇴' },
    { name: 'Peru', code: 'PE', flag: '🇵🇪' },
    { name: 'Venezuela', code: 'VE', flag: '🇻🇪' },
];

